'''
This program will read XMLs generated by the Android application "SMS Backup & Restored", and 
extract information based on the search criteria provided.

@version: 1.0.0
@author: Ian Gardea
'''

import logging
import tkinter as tk
import smsBkpXmlGUI as sbxg

if __name__ == '__main__':
   
    # Create and configure logger to auto write the time concatenated with the message.
    logging.basicConfig(filename="debug.log", 
                        format='%(asctime)s %(message)s', 
                        filemode='w') 
  
    # Create a logging object 
    logger = logging.getLogger() 

    # Set the threshold of logger to DEBUG 
    logger.setLevel(logging.DEBUG) 

    # Add to log
    logging.info("Program started")

  
    # Build the GUI
    fields = 'Date', 'Name'
    tkinter = tk.Tk()
    theGUI = sbxg.smsBkpXmlGUI()
    ents = theGUI.makeForm(tkinter, fields)
    
    # Add event listeners for key bindings
    tkinter.bind('i', (lambda event, e=ents: theGUI.printValues(e)))   
    
    # Add buttons
    b1 = tk.Button(tkinter, text='Submit', command=(lambda e=ents: theGUI.searchXml(e)))
    b1.pack(side=tk.LEFT, padx=5, pady=5)

    # Add to log
    logging.info("Successfully added Submit button to GUI.")
    
    b2 = tk.Button(tkinter, text='Quit', command=tkinter.quit)
    b2.pack(side=tk.LEFT, padx=5, pady=5)

    # Add to log
    logging.info("Successfully added Quit button to GUI.")
    
    # Run main form loop. Code outside of this will not be run until the form is closed.
    tkinter.mainloop()